# AUTHOR: Ethan Schoonbee
# EMAIL: schoonbeeethan@gmail.com
# DATE CREATED: 15/10/2024
# LAST MODIFIED: 16/10/2024

# Specifies the AWS CloudFormation template version
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to provision a Security Group for AWS Lambda functions.'

Resources:
  # Creates a Security Group for Lambda functions to control network traffic
  LambdaSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      # Describes the purpose of the Security Group
      GroupDescription: 'Security Group for allowing traffic to lambdas'
      # Associates the Security Group with the imported VPC
      VpcId: !ImportValue VPCId
      # Allows inbound TCP traffic on port 443 (HTTPS) from any IP address
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: "0.0.0.0/0"

# Resources to export and make available for use in other CloudFormation stacks
Outputs:
  # Output the Security Group ID
  LambdaSecurityGroupId:
    Description: 'Id of lambda security group'
    Value: !Ref LambdaSecurityGroup
    Export:
      Name: 'LambdaSecurityGroupId'
#____________________....oooOO0_END_OF_FILE_0OOooo....___________________