AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create a new VPC with essential components'

Resources:

  LambdaSecurityGroup:
    Type: 'AWCidrIp::SecurityGroup'
    Properties:
      GroupDescription: 'Security Group for allowing traffic to lambdas'
      VpcId: !ImportValue VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"

Outputs:

  LambdaSecurityGroupId:
    Description: 'Id of lambda security group'
    Value: !Ref LambdaSecurityGroup
    Export:
      Name: 'LambdaSecurityGroupId'